server:
  port: 9050

logging:
  path: /usr/local/spring-boot/usp-biz

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  scan: store.bymin.user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1929ksz2x1492y3.mysql.rds.aliyuncs.com:3306/ldd?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: mqfq_api2018
    password: Mqfq2018Api
    druid:
      maxActive: 500
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 35
      validationQuery:  select 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000  #（毫秒）
      minEvictableIdleTimeMillis: 25200000   #（毫秒）
      removeAbandoned: true
      removeAbandonedTimeout: 1800    #设置成你服务中service的最长运行时间（单位秒）
      logAbandoned: true
      filters: mergeStat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
  #mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  typeAliasesPackage: com.pgy.ups.account.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    #使用驼峰法映射属性
    map-underscore-to-camel-case: true
    cache-enabled: false

dubbo:
  name: ups-account-meiqi-consumers
  logger: slf4j
  address: zookeeper://127.0.0.1:2181 #zookeeper://192.168.2.116:2181
  zkClient: curator
system:
  code: "01"

